<?
    /****************************
     * Global constants.
     ****************************/


    // name of database
    define("DB", "pmdcregister");

    // username for database
    define("DBUSER", "oxbnhzx4xg0w3tgp");

    // password for database
    define("DBPASS", "mn93pbqfjds659py");

    // fully-qualified domain name (and port, e.g server:5050) of database server
    define("DBSERVER", "nj5rh9gto1v5n05t.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306");

	 // Table for User information
    define("USERS", "UserInfo");
?>
